### ISSUE TITLE
Email template didn't exist

### ISSUE THREAD

**Issue by julienanquetil** [wl-online-payments-direct/plugin-magento-core#13] opened 2023-02-01 08:03 UTC
This template didn't exist in the module, so if you try to load the template in admin it will fail.

https://github.com/wl-online-payments-direct/plugin-magento-core/blob/2d94692e39729edb1bbaa5309fe5bd45897d92cf/etc/email_templates.xml#L9

**Comment by WorldlineMagentoTeam** [comment] 2023-02-07 14:41
Hello, @julienanquetil . Thank you for the feedback.

The template is here:
https://github.com/wl-online-payments-direct/plugin-magento-core/blob/main/view/adminhtml/email/order_creation_failed.html

Could you, please, share more information about the issue? 
- What version of Magento do you use?
- What are the steps to reproduce?

Thank you!

**Comment by WorldlineMagentoTeam** [comment] 2023-02-16 15:59
Hello Julien. Thank you very much for your feedback. The issue is fixed in the 2.6.0 version.
Please, validate.

**Closed by WorldlineMagentoTeam** 2023-02-16 15:59 UTC
